version: '3'

services:
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    image: wordpress:v1
    expose:
      - "9000"
    volumes:
      - wp_data:/var/www/html/wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - mynet
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    image: mariadb:v1
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - mynet
    env_file:
      - .env

  nginx:
    container_name: nginx
    build: requirements/nginx/
    image: nginx:v1
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html/wordpress
    depends_on:
      - wordpress
    restart: always
    networks:
      - mynet
    env_file:
      - .env

networks:
  mynet:

volumes:
  wp_data:
    driver_opts: 
      device: /home/mmasubuc/data/wordpress
      type: none
      o: bind
  db_data:
    driver_opts: 
      device: /home/mmasubuc/data/mariadb
      type: none
      o: bind
