version: '3'

services:
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    ports:
      - "9000"
    volumes:
      - wp_data:/var/www/html/wordpress
    depends_on:
      - db
    restart: always
    networks:
      - mynet
    env_file:
      - .env

  db:
    container_name: mariadb
    build: requirements/mariadb/
    ports:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - mynet
    env_file:
      - .env

  server:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html/wordpress
    depends_on:
      - wordpress
    restart: always
    networks:
      - mynet
    env_file:
      - .env

networks:
  mynet:

volumes: 
  wp_data:
    driver_opts: 
      type: none
      device: /home/mmasubuc/data/wordpress
      o: bind
  db_data:
    driver_opts: 
      type: none
      device: /home/mmasubuc/data/db
      o: bind
